name: my_shop_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-49.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # for firebase
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  firebase_database: ^9.1.0
  firebase_storage: ^10.3.4
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: any
  firebase_analytics: any

  image_picker: ^0.8.5+3
  shared_preferences: any
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
