// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBInkZf0eFQvO5hM-5lUL-rz4cNJ7c_ro',
    appId: '1:135163768503:web:93f7d9048a0525ab1d6732',
    messagingSenderId: '135163768503',
    projectId: 'myshopapp-7f97c',
    authDomain: 'myshopapp-7f97c.firebaseapp.com',
    storageBucket: 'myshopapp-7f97c.appspot.com',
    measurementId: 'G-BJSRBNXP24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RDmcB8mlM-J_66BJpdQ6g9BeXVhCjd0',
    appId: '1:135163768503:android:eaba30a4a724cb4f1d6732',
    messagingSenderId: '135163768503',
    projectId: 'myshopapp-7f97c',
    storageBucket: 'myshopapp-7f97c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbPfu5rol2G4t8gSaprB_Y2I2ZZNJ874c',
    appId: '1:135163768503:ios:de802cfd0fa40aa01d6732',
    messagingSenderId: '135163768503',
    projectId: 'myshopapp-7f97c',
    storageBucket: 'myshopapp-7f97c.appspot.com',
    iosClientId: '135163768503-7el2tk6dbvop1oaipecug3v86fn7g0ps.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.myShopApp',
  );
}
